//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSegurosGAP.AccesoDatos.EFProvider.DataContext
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TestSegurosGAP.Entidades;

    public partial class TestSegurosGAPEntities : DbContext
    {
        public TestSegurosGAPEntities()
            : base("name=TestSegurosGAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Poliza> Poliza { get; set; }
        public virtual DbSet<TipoCubrimiento> TipoCubrimiento { get; set; }
        public virtual DbSet<TipoRiesgo> TipoRiesgo { get; set; }
    }
}
